name: CI
on: [push, pull_request]

concurrency: 
  group: ci
  cancel-in-progress: true
    
jobs:
    macOS:
        name: Test macOS 12
        runs-on: macOS-12
        env: DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: macOS 12
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=macOS" clean test | xcpretty

    iOS_16:
        name: Test iOS 16
        runs-on: macOS-12
        env: DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: iOS 16
              run: run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 14,OS=16.2" clean test | xcpretty

    iOS_15:
        name: Test iOS 15
        runs-on: macOS-11
        env: DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: iOS 15
              run: run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 11,OS=15.0" clean test | xcpretty

    iOS_14:
        name: Test iOS 14
        runs-on: macOS-11
        env: DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: iOS 14
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" clean test | xcpretty

    tvOS_15:
        name: Test tvOS 15
        runs-on: macOS-11
        env: DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: tvOS 15
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation),OS=15.0" clean test | xcpretty

    watchOS_8:
        name: Test watchOS 8
        runs-on: macOS-11
        env: DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: watchOS 8.0
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=watchOS Simulator,name=Apple Watch Series 7 - 45mm,OS=8.0" clean test | xcpretty
